[env]
DRIVER_NAME = "kernel-rs"
CARGO_NAME = "driver"
CARGO_MAKE_CRATE_CURRENT_WORKSPACE_MEMBER = "driver"

[env.development]
TARGET_PATH = "target/x86_64-pc-windows-msvc/debug"

[env.production]
TARGET_PATH = "target/x86_64-pc-windows-msvc/release"
BUILD_FLAGS = "--release"

[tasks.build-driver]
script = [
    "cargo b %BUILD_FLAGS%"
]

[tasks.rename]
#dependencies = ["build-driver"]
ignore_errors = true
script = [
    "cd %TARGET_PATH%",
    "cp -f %CARGO_NAME%.dll %CARGO_NAME%.sys",
]

[tasks.map]
dependencies = ["rename"]
script = [
    "kdmapper.exe %TARGET_PATH%/%CARGO_NAME%.sys"
]

[tasks.load]
dependencies = ["rename"]
script = [
    "sc stop %DRIVER_NAME%",
    "sc delete %DRIVER_NAME%",
    "sc create %DRIVER_NAME% binPath= %CARGO_MAKE_WORKING_DIRECTORY%/%TARGET_PATH%/%CARGO_NAME% type= kernel",
    "sc start %DRIVER_NAME%"
]